name: docker-compose-test
on: 
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: shellcheck
        run: docker-compose run shellcheck
      - name: ubuntu checksec
        run: docker-compose run checksec-ubuntu
      - name: arch checksec
        run: docker-compose run checksec-arch
      - name: photon checksec
        run: docker-compose run checksec-photon
      - name: docker build
        run: docker build -t slimm609/checksec:latest .
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: slimm609/checksec:latest